{
 "title": "Live",
 "time": { "from": "now-2s", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Background",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "trade_engine_background{}" }
   ]
  },
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "trade_engine_power{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current candle",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "targets": [
    { "expr": "candle_high", "legendFormat": "__auto" },
    { "expr": "candle_open", "legendFormat": "__auto" },
    { "expr": "candle_close", "legendFormat": "__auto" },
    { "expr": "candle_low", "legendFormat": "__auto" }
   ]
  }
 ]
}