apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: cfacnscusrzeof
    access: proxy
    orgId: 1
    jsonData:
      defaultDatabase: default
      protocol: native
      host: clickhouse
      port: 9000
      username: vt_user
      tlsSkipVerify: true
      logs:
        defaultDatabase: default
        defaultTable: logs
        otelEnabled: false
        timeColumn: created_at
        messageColumn: log_string
    secureJsonData:
      password: vt_pass
    isDefault: false
    editable: false