# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import vector_trader_pb2 as vector__trader__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vector_trader_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StockStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LastNCandles = channel.unary_unary(
                '/vectortrader.Stock/LastNCandles',
                request_serializer=vector__trader__pb2.LastNRequest.SerializeToString,
                response_deserializer=vector__trader__pb2.LastNResponse.FromString,
                _registered_method=True)
        self.IntervalCandles = channel.unary_unary(
                '/vectortrader.Stock/IntervalCandles',
                request_serializer=vector__trader__pb2.IntervalCandlesRequest.SerializeToString,
                response_deserializer=vector__trader__pb2.IntervalCandlesResponse.FromString,
                _registered_method=True)
        self.OpenOrder = channel.unary_unary(
                '/vectortrader.Stock/OpenOrder',
                request_serializer=vector__trader__pb2.OpenOrderRequest.SerializeToString,
                response_deserializer=vector__trader__pb2.OpenOrderResponse.FromString,
                _registered_method=True)
        self.CloseOrder = channel.unary_unary(
                '/vectortrader.Stock/CloseOrder',
                request_serializer=vector__trader__pb2.CloseOrderRequest.SerializeToString,
                response_deserializer=vector__trader__pb2.CloseOrderResponse.FromString,
                _registered_method=True)


class StockServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LastNCandles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IntervalCandles(self, request, context):
        """rpc GetHistory(HistoryRequest) returns (stream HistoryResponse); deprecated use IntervalCandles
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StockServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LastNCandles': grpc.unary_unary_rpc_method_handler(
                    servicer.LastNCandles,
                    request_deserializer=vector__trader__pb2.LastNRequest.FromString,
                    response_serializer=vector__trader__pb2.LastNResponse.SerializeToString,
            ),
            'IntervalCandles': grpc.unary_unary_rpc_method_handler(
                    servicer.IntervalCandles,
                    request_deserializer=vector__trader__pb2.IntervalCandlesRequest.FromString,
                    response_serializer=vector__trader__pb2.IntervalCandlesResponse.SerializeToString,
            ),
            'OpenOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenOrder,
                    request_deserializer=vector__trader__pb2.OpenOrderRequest.FromString,
                    response_serializer=vector__trader__pb2.OpenOrderResponse.SerializeToString,
            ),
            'CloseOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseOrder,
                    request_deserializer=vector__trader__pb2.CloseOrderRequest.FromString,
                    response_serializer=vector__trader__pb2.CloseOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vectortrader.Stock', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vectortrader.Stock', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Stock(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LastNCandles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectortrader.Stock/LastNCandles',
            vector__trader__pb2.LastNRequest.SerializeToString,
            vector__trader__pb2.LastNResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IntervalCandles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectortrader.Stock/IntervalCandles',
            vector__trader__pb2.IntervalCandlesRequest.SerializeToString,
            vector__trader__pb2.IntervalCandlesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectortrader.Stock/OpenOrder',
            vector__trader__pb2.OpenOrderRequest.SerializeToString,
            vector__trader__pb2.OpenOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectortrader.Stock/CloseOrder',
            vector__trader__pb2.CloseOrderRequest.SerializeToString,
            vector__trader__pb2.CloseOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Decide = channel.unary_unary(
                '/vectortrader.Engine/Decide',
                request_serializer=vector__trader__pb2.DecideRequest.SerializeToString,
                response_deserializer=vector__trader__pb2.DecideResponse.FromString,
                _registered_method=True)


class EngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Decide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Decide': grpc.unary_unary_rpc_method_handler(
                    servicer.Decide,
                    request_deserializer=vector__trader__pb2.DecideRequest.FromString,
                    response_serializer=vector__trader__pb2.DecideResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vectortrader.Engine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vectortrader.Engine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Engine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Decide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectortrader.Engine/Decide',
            vector__trader__pb2.DecideRequest.SerializeToString,
            vector__trader__pb2.DecideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
