// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: vector_trader.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CandleAction int32

const (
	CandleAction_NONE CandleAction = 0
	CandleAction_BUY  CandleAction = 1
	CandleAction_SELL CandleAction = 2
)

// Enum value maps for CandleAction.
var (
	CandleAction_name = map[int32]string{
		0: "NONE",
		1: "BUY",
		2: "SELL",
	}
	CandleAction_value = map[string]int32{
		"NONE": 0,
		"BUY":  1,
		"SELL": 2,
	}
)

func (x CandleAction) Enum() *CandleAction {
	p := new(CandleAction)
	*p = x
	return p
}

func (x CandleAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CandleAction) Descriptor() protoreflect.EnumDescriptor {
	return file_vector_trader_proto_enumTypes[0].Descriptor()
}

func (CandleAction) Type() protoreflect.EnumType {
	return &file_vector_trader_proto_enumTypes[0]
}

func (x CandleAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CandleAction.Descriptor instead.
func (CandleAction) EnumDescriptor() ([]byte, []int) {
	return file_vector_trader_proto_rawDescGZIP(), []int{0}
}

type MarketAction int32

const (
	MarketAction_HOLD            MarketAction = 0
	MarketAction_OPEN            MarketAction = 1
	MarketAction_CLOSE           MarketAction = 2
	MarketAction_CLOSE_THEN_OPEN MarketAction = 3
)

// Enum value maps for MarketAction.
var (
	MarketAction_name = map[int32]string{
		0: "HOLD",
		1: "OPEN",
		2: "CLOSE",
		3: "CLOSE_THEN_OPEN",
	}
	MarketAction_value = map[string]int32{
		"HOLD":            0,
		"OPEN":            1,
		"CLOSE":           2,
		"CLOSE_THEN_OPEN": 3,
	}
)

func (x MarketAction) Enum() *MarketAction {
	p := new(MarketAction)
	*p = x
	return p
}

func (x MarketAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarketAction) Descriptor() protoreflect.EnumDescriptor {
	return file_vector_trader_proto_enumTypes[1].Descriptor()
}

func (MarketAction) Type() protoreflect.EnumType {
	return &file_vector_trader_proto_enumTypes[1]
}

func (x MarketAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarketAction.Descriptor instead.
func (MarketAction) EnumDescriptor() ([]byte, []int) {
	return file_vector_trader_proto_rawDescGZIP(), []int{1}
}

type LastNRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Interval      string                 `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastNRequest) Reset() {
	*x = LastNRequest{}
	mi := &file_vector_trader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastNRequest) ProtoMessage() {}

func (x *LastNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_trader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastNRequest.ProtoReflect.Descriptor instead.
func (*LastNRequest) Descriptor() ([]byte, []int) {
	return file_vector_trader_proto_rawDescGZIP(), []int{0}
}

func (x *LastNRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *LastNRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *LastNRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LastNResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candles       []*Candle              `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastNResponse) Reset() {
	*x = LastNResponse{}
	mi := &file_vector_trader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastNResponse) ProtoMessage() {}

func (x *LastNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_trader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastNResponse.ProtoReflect.Descriptor instead.
func (*LastNResponse) Descriptor() ([]byte, []int) {
	return file_vector_trader_proto_rawDescGZIP(), []int{1}
}

func (x *LastNResponse) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

type IntervalCandlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Interval      string                 `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	FromTimestamp int64                  `protobuf:"varint,3,opt,name=from_timestamp,json=fromTimestamp,proto3" json:"from_timestamp,omitempty"`
	ToTimestamp   int64                  `protobuf:"varint,4,opt,name=to_timestamp,json=toTimestamp,proto3" json:"to_timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntervalCandlesRequest) Reset() {
	*x = IntervalCandlesRequest{}
	mi := &file_vector_trader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntervalCandlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntervalCandlesRequest) ProtoMessage() {}

func (x *IntervalCandlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_trader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntervalCandlesRequest.ProtoReflect.Descriptor instead.
func (*IntervalCandlesRequest) Descriptor() ([]byte, []int) {
	return file_vector_trader_proto_rawDescGZIP(), []int{2}
}

func (x *IntervalCandlesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *IntervalCandlesRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *IntervalCandlesRequest) GetFromTimestamp() int64 {
	if x != nil {
		return x.FromTimestamp
	}
	return 0
}

func (x *IntervalCandlesRequest) GetToTimestamp() int64 {
	if x != nil {
		return x.ToTimestamp
	}
	return 0
}

type IntervalCandlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candles       []*Candle              `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntervalCandlesResponse) Reset() {
	*x = IntervalCandlesResponse{}
	mi := &file_vector_trader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntervalCandlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntervalCandlesResponse) ProtoMessage() {}

func (x *IntervalCandlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_trader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntervalCandlesResponse.ProtoReflect.Descriptor instead.
func (*IntervalCandlesResponse) Descriptor() ([]byte, []int) {
	return file_vector_trader_proto_rawDescGZIP(), []int{3}
}

func (x *IntervalCandlesResponse) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

type DecideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candle        *Candle                `protobuf:"bytes,1,opt,name=candle,proto3" json:"candle,omitempty"`
	Spread        float64                `protobuf:"fixed64,2,opt,name=spread,proto3" json:"spread,omitempty"`
	Balance       float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideRequest) Reset() {
	*x = DecideRequest{}
	mi := &file_vector_trader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideRequest) ProtoMessage() {}

func (x *DecideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_trader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideRequest.ProtoReflect.Descriptor instead.
func (*DecideRequest) Descriptor() ([]byte, []int) {
	return file_vector_trader_proto_rawDescGZIP(), []int{4}
}

func (x *DecideRequest) GetCandle() *Candle {
	if x != nil {
		return x.Candle
	}
	return nil
}

func (x *DecideRequest) GetSpread() float64 {
	if x != nil {
		return x.Spread
	}
	return 0
}

func (x *DecideRequest) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type DecideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketAction  MarketAction           `protobuf:"varint,1,opt,name=market_action,json=marketAction,proto3,enum=vectortrader.MarketAction" json:"market_action,omitempty"`
	Order         *Order                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	Profit        float64                `protobuf:"fixed64,3,opt,name=profit,proto3" json:"profit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideResponse) Reset() {
	*x = DecideResponse{}
	mi := &file_vector_trader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideResponse) ProtoMessage() {}

func (x *DecideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_trader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideResponse.ProtoReflect.Descriptor instead.
func (*DecideResponse) Descriptor() ([]byte, []int) {
	return file_vector_trader_proto_rawDescGZIP(), []int{5}
}

func (x *DecideResponse) GetMarketAction() MarketAction {
	if x != nil {
		return x.MarketAction
	}
	return MarketAction_HOLD
}

func (x *DecideResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *DecideResponse) GetProfit() float64 {
	if x != nil {
		return x.Profit
	}
	return 0
}

type OpenOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Order         *Order                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenOrderRequest) Reset() {
	*x = OpenOrderRequest{}
	mi := &file_vector_trader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenOrderRequest) ProtoMessage() {}

func (x *OpenOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_trader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenOrderRequest.ProtoReflect.Descriptor instead.
func (*OpenOrderRequest) Descriptor() ([]byte, []int) {
	return file_vector_trader_proto_rawDescGZIP(), []int{6}
}

func (x *OpenOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OpenOrderRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type OpenOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenOrderResponse) Reset() {
	*x = OpenOrderResponse{}
	mi := &file_vector_trader_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenOrderResponse) ProtoMessage() {}

func (x *OpenOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_trader_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenOrderResponse.ProtoReflect.Descriptor instead.
func (*OpenOrderResponse) Descriptor() ([]byte, []int) {
	return file_vector_trader_proto_rawDescGZIP(), []int{7}
}

func (x *OpenOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CloseOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseOrderRequest) Reset() {
	*x = CloseOrderRequest{}
	mi := &file_vector_trader_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseOrderRequest) ProtoMessage() {}

func (x *CloseOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_trader_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseOrderRequest.ProtoReflect.Descriptor instead.
func (*CloseOrderRequest) Descriptor() ([]byte, []int) {
	return file_vector_trader_proto_rawDescGZIP(), []int{8}
}

func (x *CloseOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type CloseOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profit        float64                `protobuf:"fixed64,1,opt,name=profit,proto3" json:"profit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseOrderResponse) Reset() {
	*x = CloseOrderResponse{}
	mi := &file_vector_trader_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseOrderResponse) ProtoMessage() {}

func (x *CloseOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_trader_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseOrderResponse.ProtoReflect.Descriptor instead.
func (*CloseOrderResponse) Descriptor() ([]byte, []int) {
	return file_vector_trader_proto_rawDescGZIP(), []int{9}
}

func (x *CloseOrderResponse) GetProfit() float64 {
	if x != nil {
		return x.Profit
	}
	return 0
}

type Candle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Open          float64                `protobuf:"fixed64,1,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,2,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,3,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,4,opt,name=close,proto3" json:"close,omitempty"`
	Volume        float64                `protobuf:"fixed64,5,opt,name=volume,proto3" json:"volume,omitempty"`
	OpenTime      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	CloseTime     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candle) Reset() {
	*x = Candle{}
	mi := &file_vector_trader_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candle) ProtoMessage() {}

func (x *Candle) ProtoReflect() protoreflect.Message {
	mi := &file_vector_trader_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candle.ProtoReflect.Descriptor instead.
func (*Candle) Descriptor() ([]byte, []int) {
	return file_vector_trader_proto_rawDescGZIP(), []int{10}
}

func (x *Candle) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Candle) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Candle) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Candle) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Candle) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Candle) GetOpenTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OpenTime
	}
	return nil
}

func (x *Candle) GetCloseTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CloseTime
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         float64                `protobuf:"fixed64,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Sl            float64                `protobuf:"fixed64,2,opt,name=sl,proto3" json:"sl,omitempty"`
	Tp            float64                `protobuf:"fixed64,3,opt,name=tp,proto3" json:"tp,omitempty"`
	CandleAction  CandleAction           `protobuf:"varint,4,opt,name=candle_action,json=candleAction,proto3,enum=vectortrader.CandleAction" json:"candle_action,omitempty"`
	Volume        float64                `protobuf:"fixed64,5,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_vector_trader_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_vector_trader_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_vector_trader_proto_rawDescGZIP(), []int{11}
}

func (x *Order) GetEntry() float64 {
	if x != nil {
		return x.Entry
	}
	return 0
}

func (x *Order) GetSl() float64 {
	if x != nil {
		return x.Sl
	}
	return 0
}

func (x *Order) GetTp() float64 {
	if x != nil {
		return x.Tp
	}
	return 0
}

func (x *Order) GetCandleAction() CandleAction {
	if x != nil {
		return x.CandleAction
	}
	return CandleAction_NONE
}

func (x *Order) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

var File_vector_trader_proto protoreflect.FileDescriptor

const file_vector_trader_proto_rawDesc = "" +
	"\n" +
	"\x13vector_trader.proto\x12\fvectortrader\x1a\x1fgoogle/protobuf/timestamp.proto\"X\n" +
	"\fLastNRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\tR\binterval\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"?\n" +
	"\rLastNResponse\x12.\n" +
	"\acandles\x18\x01 \x03(\v2\x14.vectortrader.CandleR\acandles\"\x96\x01\n" +
	"\x16IntervalCandlesRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\tR\binterval\x12%\n" +
	"\x0efrom_timestamp\x18\x03 \x01(\x03R\rfromTimestamp\x12!\n" +
	"\fto_timestamp\x18\x04 \x01(\x03R\vtoTimestamp\"I\n" +
	"\x17IntervalCandlesResponse\x12.\n" +
	"\acandles\x18\x01 \x03(\v2\x14.vectortrader.CandleR\acandles\"o\n" +
	"\rDecideRequest\x12,\n" +
	"\x06candle\x18\x01 \x01(\v2\x14.vectortrader.CandleR\x06candle\x12\x16\n" +
	"\x06spread\x18\x02 \x01(\x01R\x06spread\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x01R\abalance\"\x94\x01\n" +
	"\x0eDecideResponse\x12?\n" +
	"\rmarket_action\x18\x01 \x01(\x0e2\x1a.vectortrader.MarketActionR\fmarketAction\x12)\n" +
	"\x05order\x18\x02 \x01(\v2\x13.vectortrader.OrderR\x05order\x12\x16\n" +
	"\x06profit\x18\x03 \x01(\x01R\x06profit\"U\n" +
	"\x10OpenOrderRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12)\n" +
	"\x05order\x18\x02 \x01(\v2\x13.vectortrader.OrderR\x05order\".\n" +
	"\x11OpenOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"+\n" +
	"\x11CloseOrderRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\",\n" +
	"\x12CloseOrderResponse\x12\x16\n" +
	"\x06profit\x18\x01 \x01(\x01R\x06profit\"\xe4\x01\n" +
	"\x06Candle\x12\x12\n" +
	"\x04open\x18\x01 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x02 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x03 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x04 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x01R\x06volume\x127\n" +
	"\topen_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bopenTime\x129\n" +
	"\n" +
	"close_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcloseTime\"\x96\x01\n" +
	"\x05Order\x12\x14\n" +
	"\x05entry\x18\x01 \x01(\x01R\x05entry\x12\x0e\n" +
	"\x02sl\x18\x02 \x01(\x01R\x02sl\x12\x0e\n" +
	"\x02tp\x18\x03 \x01(\x01R\x02tp\x12?\n" +
	"\rcandle_action\x18\x04 \x01(\x0e2\x1a.vectortrader.CandleActionR\fcandleAction\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x01R\x06volume*+\n" +
	"\fCandleAction\x12\b\n" +
	"\x04NONE\x10\x00\x12\a\n" +
	"\x03BUY\x10\x01\x12\b\n" +
	"\x04SELL\x10\x02*B\n" +
	"\fMarketAction\x12\b\n" +
	"\x04HOLD\x10\x00\x12\b\n" +
	"\x04OPEN\x10\x01\x12\t\n" +
	"\x05CLOSE\x10\x02\x12\x13\n" +
	"\x0fCLOSE_THEN_OPEN\x10\x032\xcf\x02\n" +
	"\x05Stock\x12G\n" +
	"\fLastNCandles\x12\x1a.vectortrader.LastNRequest\x1a\x1b.vectortrader.LastNResponse\x12^\n" +
	"\x0fIntervalCandles\x12$.vectortrader.IntervalCandlesRequest\x1a%.vectortrader.IntervalCandlesResponse\x12L\n" +
	"\tOpenOrder\x12\x1e.vectortrader.OpenOrderRequest\x1a\x1f.vectortrader.OpenOrderResponse\x12O\n" +
	"\n" +
	"CloseOrder\x12\x1f.vectortrader.CloseOrderRequest\x1a .vectortrader.CloseOrderResponse2M\n" +
	"\x06Engine\x12C\n" +
	"\x06Decide\x12\x1b.vectortrader.DecideRequest\x1a\x1c.vectortrader.DecideResponseB:Z8github.com/vector-trader/stock-interactor/internal/pb;pbb\x06proto3"

var (
	file_vector_trader_proto_rawDescOnce sync.Once
	file_vector_trader_proto_rawDescData []byte
)

func file_vector_trader_proto_rawDescGZIP() []byte {
	file_vector_trader_proto_rawDescOnce.Do(func() {
		file_vector_trader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vector_trader_proto_rawDesc), len(file_vector_trader_proto_rawDesc)))
	})
	return file_vector_trader_proto_rawDescData
}

var file_vector_trader_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_vector_trader_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_vector_trader_proto_goTypes = []any{
	(CandleAction)(0),               // 0: vectortrader.CandleAction
	(MarketAction)(0),               // 1: vectortrader.MarketAction
	(*LastNRequest)(nil),            // 2: vectortrader.LastNRequest
	(*LastNResponse)(nil),           // 3: vectortrader.LastNResponse
	(*IntervalCandlesRequest)(nil),  // 4: vectortrader.IntervalCandlesRequest
	(*IntervalCandlesResponse)(nil), // 5: vectortrader.IntervalCandlesResponse
	(*DecideRequest)(nil),           // 6: vectortrader.DecideRequest
	(*DecideResponse)(nil),          // 7: vectortrader.DecideResponse
	(*OpenOrderRequest)(nil),        // 8: vectortrader.OpenOrderRequest
	(*OpenOrderResponse)(nil),       // 9: vectortrader.OpenOrderResponse
	(*CloseOrderRequest)(nil),       // 10: vectortrader.CloseOrderRequest
	(*CloseOrderResponse)(nil),      // 11: vectortrader.CloseOrderResponse
	(*Candle)(nil),                  // 12: vectortrader.Candle
	(*Order)(nil),                   // 13: vectortrader.Order
	(*timestamppb.Timestamp)(nil),   // 14: google.protobuf.Timestamp
}
var file_vector_trader_proto_depIdxs = []int32{
	12, // 0: vectortrader.LastNResponse.candles:type_name -> vectortrader.Candle
	12, // 1: vectortrader.IntervalCandlesResponse.candles:type_name -> vectortrader.Candle
	12, // 2: vectortrader.DecideRequest.candle:type_name -> vectortrader.Candle
	1,  // 3: vectortrader.DecideResponse.market_action:type_name -> vectortrader.MarketAction
	13, // 4: vectortrader.DecideResponse.order:type_name -> vectortrader.Order
	13, // 5: vectortrader.OpenOrderRequest.order:type_name -> vectortrader.Order
	14, // 6: vectortrader.Candle.open_time:type_name -> google.protobuf.Timestamp
	14, // 7: vectortrader.Candle.close_time:type_name -> google.protobuf.Timestamp
	0,  // 8: vectortrader.Order.candle_action:type_name -> vectortrader.CandleAction
	2,  // 9: vectortrader.Stock.LastNCandles:input_type -> vectortrader.LastNRequest
	4,  // 10: vectortrader.Stock.IntervalCandles:input_type -> vectortrader.IntervalCandlesRequest
	8,  // 11: vectortrader.Stock.OpenOrder:input_type -> vectortrader.OpenOrderRequest
	10, // 12: vectortrader.Stock.CloseOrder:input_type -> vectortrader.CloseOrderRequest
	6,  // 13: vectortrader.Engine.Decide:input_type -> vectortrader.DecideRequest
	3,  // 14: vectortrader.Stock.LastNCandles:output_type -> vectortrader.LastNResponse
	5,  // 15: vectortrader.Stock.IntervalCandles:output_type -> vectortrader.IntervalCandlesResponse
	9,  // 16: vectortrader.Stock.OpenOrder:output_type -> vectortrader.OpenOrderResponse
	11, // 17: vectortrader.Stock.CloseOrder:output_type -> vectortrader.CloseOrderResponse
	7,  // 18: vectortrader.Engine.Decide:output_type -> vectortrader.DecideResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_vector_trader_proto_init() }
func file_vector_trader_proto_init() {
	if File_vector_trader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vector_trader_proto_rawDesc), len(file_vector_trader_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_vector_trader_proto_goTypes,
		DependencyIndexes: file_vector_trader_proto_depIdxs,
		EnumInfos:         file_vector_trader_proto_enumTypes,
		MessageInfos:      file_vector_trader_proto_msgTypes,
	}.Build()
	File_vector_trader_proto = out.File
	file_vector_trader_proto_goTypes = nil
	file_vector_trader_proto_depIdxs = nil
}
